name: Run Python Project

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Build da imagem Docker
    - name: Build Docker image
      run: docker build -t my-python-app .

    # Executa o contêiner e monta um volume compartilhado com o sistema de arquivos do runner
    - name: Run Python script in Docker container
      run: |
        mkdir -p ./output  # Cria uma pasta local para salvar o arquivo
        docker run -v $(pwd)/output:/app/output my-python-app

    # Upload do arquivo Parquet gerado
    - name: Upload Parquet files
      uses: actions/upload-artifact@v3
      with:
        name: openaq-data-files
        path: ./output/*_openaq_data*.parquet
