name: Run Python Project

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Docker no runner
    - name: Build Docker image
      run: docker build -t my-python-app .

    # Executa o contêiner com o script Python que gera o arquivo Parquet
    - name: Run Python script in Docker container
      run: docker run my-python-app

    # Salva o arquivo Parquet gerado como artifact
    - name: Upload Parquet file
      uses: actions/upload-artifact@v3
      with:
        name: parquet-file  # Nome do artifact
        path: "*_openaq_data*.parquet"  # Caminho do arquivo Parquet gerado
